#pragma once

#include "io/IFileWriter.h"
#include <string>
#include <atomic>

namespace koomesh {
namespace io {

/**
 * @brief Nastran BDF (Bulk Data File) format writer
 *
 * TODO: This is a stub implementation for future Nastran format support.
 *
 * Nastran BDF output format:
 * - Support free-field (comma-separated) and fixed-field formats
 * - Write GRID cards for nodes
 * - Write element cards (CTETRA, CHEXA, CTRIA3, CQUAD4, etc.)
 * - Optionally write PSOLID/PSHELL property cards
 * - Optionally write MAT1 material cards
 *
 * Example output:
 * @code
 * $  Nastran Bulk Data File
 * $  Generated by KooMeshPrepost
 * BEGIN BULK
 * $  Nodes
 * GRID,1,,0.0,0.0,0.0
 * GRID,2,,1.0,0.0,0.0
 * $  Elements
 * CTETRA,100,1,1,2,3,4
 * ENDDATA
 * @endcode
 *
 * Implementation notes:
 * - Use free-field format by default (easier to read/write)
 * - Support fixed-field format as option
 * - Handle field width and alignment for fixed format
 * - Write continuation lines for elements with many nodes
 * - Map ElementType to Nastran element types:
 *   - TRIANGLE -> CTRIA3
 *   - QUADRILATERAL -> CQUAD4
 *   - TETRAHEDRON -> CTETRA
 *   - HEXAHEDRON -> CHEXA
 *   - PENTAHEDRON -> CPENTA
 *   - PYRAMID -> CPYRAM
 *
 * @see https://web.mit.edu/calculix_v2.7/CalculiX/ccx_2.7/doc/ccx/node252.html
 */
class NastranFileWriter : public IFileWriter {
public:
    NastranFileWriter();
    ~NastranFileWriter() override;

    // IFileWriter interface
    bool canWrite(const std::string& filename) const override;
    std::vector<std::string> supportedExtensions() const override;
    std::string formatName() const override;

    WriteResult write(
        const std::string& filename,
        const core::Mesh& mesh,
        const WriteOptions& options = WriteOptions(),
        ProgressCallback progressCallback = nullptr
    ) override;

    double progress() const override;
    void cancel() override;
    bool isWriting() const override;

private:
    std::atomic<double> m_progress;
    std::atomic<bool> m_cancelRequested;
    std::atomic<bool> m_isWriting;
};

/**
 * @brief Register Nastran writer with factory
 */
void registerNastranWriter();

} // namespace io
} // namespace koomesh
